#! /bin/bash

testname=$( basename "$0" )
testmethod="get"
testaddress="10650+W+Charleston+Blvd,+Las+Vegas,+NV+89135"
testpath="/services/v1/representatives?address=\"$testaddress\""

time wget --header="APIKey: v1key"  \
     --method="$testmethod" -S -O "$testname.log" \
     http://${GADFLY_SERVERIP:=127.0.0.1:5000}${testpath}
